modLoader= "javafml" 
loaderVersion= "${loader_version_range}"
license= "${mod_license}"

[[mods]] 
modId= "patchouli_plus"
version= "${mod_version}"
displayName= "Patchouli++"
authors= "Tortugolen"
description= '''Patchouli Extras'''

[[dependencies.patchouli_plus]]
modId= "minecraft"
mandatory= true
versionRange= "${minecraft_version_range}"
ordering= "NONE"
side= "BOTH"

[[dependencies.patchouli_plus]]
modId= "forge" 
mandatory= true 
versionRange= "${forge_version_range}"
ordering= "NONE"
side= "BOTH"

[[dependencies.patchouli_plus]]
modId= "patchouli"
mandatory= true
versionRange= "${patchouli_version_range}"
ordering= "NONE"
side= "BOTH"